apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ibirdos
resources: [../../base]
patchesStrategicMerge: [replicas.yaml]
images:
  - name: ghcr.io/ibirdos/api
    newTag: v1.0.0
  - name: ghcr.io/ibirdos/web
    newTag: v1.0.0
  - name: ghcr.io/ibirdos/workers
    newTag: v1.0.0
