apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ibirdos
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Security: max-age=63072000; includeSubDomains; preload";
spec:
  ingressClassName: nginx
  tls:
    - hosts: [app.ibirdos.com, api.ibirdos.com]
      secretName: ibirdos-tls
  rules:
    - host: app.ibirdos.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: web, port: { number: 3000 } } }
    - host: api.ibirdos.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: api, port: { number: 3001 } } }
          - path: /socket.io
            pathType: Prefix
            backend: { service: { name: api, port: { number: 3002 } } }
