apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ibirdos
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-statefulset.yaml
  - redis-statefulset.yaml
  - api-deployment.yaml
  - api-service.yaml
  - workers-deployment.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml
  - hpa.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - migration-job.yaml
